# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle


name: Java Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Extract mod version
        id: extract_version
        run: |
          VERSION=$(./gradlew printModVersion --quiet)
          echo "::set-output name=version::$VERSION"

      - name: Build File
        run: |
          chmod +x gradlew 
          ./gradlew build

      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: HeliosClient
          path: build/libs/heliosclient-${{ steps.extract_version.outputs.version }}.jar
